name = "mem-cnm-wk"
main = "worker.js"
compatibility_date = "2024-12-18"
workers_dev = false
rules = [
  { type = "ESModule", globs = ["**/*.js"], fallthrough = true }
]

[[kv_namespaces]]
binding = "blog"
id = "BLOG_KV_DATA"

[placement]
mode = "smart"