name = "mem-cnm-wk"
main = "worker.js"
compatibility_date = "2024-12-18"
workers_dev = false
rules = [
  { type = "ESModule", globs = ["**/*.js"], fallthrough = true }
]

[[kv_namespaces]]
binding = "blog"
id = "08e73cb0571e4c55940ac75bc2a38eb8"

[placement]
mode = "smart"