name: Build and Deploy Worker

on:
  push:
  schedule:
    - cron: '1 0,4,8,12,16,20 * * *'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: 'renew'
        run: bash ./renew.sh

      - name: Commit and push built worker
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add _worker.js
          git commit -m "Automated build: update _worker.js"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
