name: Cloudflare Worker Deploy
on:
  push:
    branches:
      - main
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: '10 */18 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Rename Workerjs
        run: |
          mv _worker275.js worker.js
      - name: Delete Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: 'delete --name mem-cmm-wk-old'
      - name: Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          # accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: 'deploy --keep-vars --var uid:${{ secrets.CF_UUID }} BLOG_PWD:${{ secrets.CF_TROJANT_PWD }} --env tag_275 --name mem-cmm-wk-old'
